#### INITIAL REPO SETUP ####

# set username
sysuser@ubuntuprod:~/git/alinuxuser (master -> origin/master)$ git config user.name "RC"

# set email
sysuser@ubuntuprod:~/git/alinuxuser (master -> origin/master)$ git config user.email "alinuxuser@fastmail.com"

# rebase when pulling
git config pull.rebase true

# create local branch named dev
git checkout -b dev

# set upstream branch to dev
git push -u origin dev



