[build]
publish = "public"
command = """\
  curl -sLJO "https://github.com/sass/dart-sass/releases/download/1.99.0/dart-sass-1.99.0-linux-x64.tar.gz" && \
  tar -C "${HOME}/.local" -xf "dart-sass-1.99.0-linux-x64.tar.gz" && \
  rm "dart-sass-1.99.0-linux-x64.tar.gz" && \
  export PATH="${HOME}/.local/dart-sass:${PATH}" && \
  hugo --gc --minify
"""

[build.environment]
HUGO_VERSION = "0.161.1"
GO_VERSION = "1.26.1"
NODE_VERSION = "24.14.1"
HUGO_ENV = "production"
TZ = "America/Chicago"
